<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Producto;

use Atlas\Table\Table;

/**
 * @method ProductoRow|null fetchRow($primaryVal)
 * @method ProductoRow[] fetchRows(array $primaryVals)
 * @method ProductoTableSelect select(array $whereEquals = [])
 * @method ProductoRow newRow(array $cols = [])
 * @method ProductoRow newSelectedRow(array $cols)
 */
class ProductoTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'productos';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'sku' => [
            'name' => 'sku',
            'type' => 'varchar',
            'size' => 20,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'nombre' => [
            'name' => 'nombre',
            'type' => 'varchar',
            'size' => 80,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'marca' => [
            'name' => 'marca',
            'type' => 'varchar',
            'size' => 50,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'precio' => [
            'name' => 'precio',
            'type' => 'decimal',
            'size' => 15,
            'scale' => 2,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created' => [
            'name' => 'created',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'modified' => [
            'name' => 'modified',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'estado' => [
            'name' => 'estado',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 1,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'sku',
        'nombre',
        'marca',
        'precio',
        'created',
        'modified',
        'estado',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'sku' => null,
        'nombre' => null,
        'marca' => null,
        'precio' => null,
        'created' => null,
        'modified' => null,
        'estado' => 1,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
