<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\Producto;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $sku varchar(20) NOT NULL
 * @property mixed $nombre varchar(80) NOT NULL
 * @property mixed $marca varchar(50) NOT NULL
 * @property mixed $precio decimal(15,2) NOT NULL
 * @property mixed $created datetime NOT NULL
 * @property mixed $modified datetime NOT NULL
 * @property mixed $estado tinyint(3,0) NOT NULL
 */
class ProductoRow extends Row
{
    protected $cols = [
        'id' => null,
        'sku' => null,
        'nombre' => null,
        'marca' => null,
        'precio' => null,
        'created' => null,
        'modified' => null,
        'estado' => 1,
    ];
}
