<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\ProductoCategoria;

use Atlas\Table\Row;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $producto_id int(10,0) NOT NULL
 * @property mixed $categoria_id int(10,0) NOT NULL
 * @property mixed $created datetime NOT NULL
 * @property mixed $modified datetime NOT NULL
 * @property mixed $estado tinyint(3,0) NOT NULL
 */
class ProductoCategoriaRow extends Row
{
    protected $cols = [
        'id' => null,
        'producto_id' => null,
        'categoria_id' => null,
        'created' => null,
        'modified' => null,
        'estado' => 1,
    ];
}
