<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\ProductoCategoria;

use Atlas\Table\Table;

/**
 * @method ProductoCategoriaRow|null fetchRow($primaryVal)
 * @method ProductoCategoriaRow[] fetchRows(array $primaryVals)
 * @method ProductoCategoriaTableSelect select(array $whereEquals = [])
 * @method ProductoCategoriaRow newRow(array $cols = [])
 * @method ProductoCategoriaRow newSelectedRow(array $cols)
 */
class ProductoCategoriaTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'producto_categorias';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'int unsigned',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'producto_id' => [
            'name' => 'producto_id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'categoria_id' => [
            'name' => 'categoria_id',
            'type' => 'int',
            'size' => 10,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created' => [
            'name' => 'created',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'modified' => [
            'name' => 'modified',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'estado' => [
            'name' => 'estado',
            'type' => 'tinyint',
            'size' => 3,
            'scale' => 0,
            'notnull' => true,
            'default' => 1,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'producto_id',
        'categoria_id',
        'created',
        'modified',
        'estado',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'producto_id' => null,
        'categoria_id' => null,
        'created' => null,
        'modified' => null,
        'estado' => 1,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
