<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace DataSource\ProductoCategoria;

/**
 * @property mixed $id int(10,0) unsigned NOT NULL
 * @property mixed $producto_id int(10,0) NOT NULL
 * @property mixed $categoria_id int(10,0) NOT NULL
 * @property mixed $created datetime NOT NULL
 * @property mixed $modified datetime NOT NULL
 * @property mixed $estado tinyint(3,0) NOT NULL
 */
trait ProductoCategoriaFields
{
}
